include: package:flutter_lints/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    avoid_print: false # Allowing print for Supabase logging as requested in code
